### ISSUE TITLE
onElementAllowOperations not restricting the operation first time when question is addedvia toolbox in V2

### ISSUE THREAD

**Issue by vikkrantxx7** [surveyjs/survey-creator#1605]
### Are you requesting a feature, reporting a bug or ask a question?

Reporting a bug.

### What is the current behavior?

When some operations are not allowed and the question is added through the toolbox then the action buttons still show up.
After changing to some other element then coming back the restricted action buttons are gone.

### What is the expected behavior?

The disallowed action buttons should not show even for the first time when the question is added.

### How would you reproduce the current behavior (if this is a bug)?

Providing the plunker example.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:  https://plnkr.co/edit/n0tn5332nByf1gNu

Test code

```
// checked for text and radiogroup
creator.onElementAllowOperations.add((sender, options) => {
  if (['text', 'radiogroup'].includes(options.obj.getType())) {
    options.allowChangeType = false
    options.allowChangeRequired = false
  }
});

```

### Specify your

* browser: chrome 92
* editor version: 1.8.59-alpha.1

**Comment by andrewtelnov** [comment]
@vikkrantxx7 I was not able to reproduce the issue on the latest source. In fact, I have added a new unit test that I have commited, you can see it above, and I found out that it works without errors.
After that I have tried to reproduce it and failed to do it. I am pretty sure it has been fixed in the current build.

Thank you,
Andrew

**Comment by vikkrantxx7** [comment]
@andrewtelnov yes it has been fixed in the current build.

**Comment by vikkrantxx7** [comment]
@andrewtelnov now this is reproducible in the current build when the question is dragged and dropped from anywhere.

**Comment by tsv2013** [comment]
reproduced. moved into todo list

**Comment by vikkrantxx7** [comment]
@tsv2013 this is marked as fixed but this is still occurring for the current dev build. The commit above I think it is not related.

**Comment by tsv2013** [comment]
@vikkrantxx7 site was not updated yet due to functional tests fail for VueJS. If you want to check the fix right now you can build our libraries from the source code.

**Comment by tsv2013** [comment]
@vikkrantxx7 site has been updated. you can check the fix
