### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-creator#633]
### Are you requesting a feature, reporting a bug or asking a question?
Bug

### What is the current behavior?
When switching between JSON Editor and Survey Designer tabs memory usage quickly increases (especially for lager surveys).

### What is the expected behavior?
While I understand parsing a large JSON blob can take some time, there is no reason for memory usage to increase with 50MB each time I go back and forth between designer and editor. 

### How would you reproduce the current behavior (if this is a bug)?
1. Use this JSON: https://gist.github.com/SamMousa/e58b4a39cc42252484b1ea96455ca52f
2. Go to the creator in an incognito window: https://surveyjs.io/create-survey/
3. Paste the JSON
4. Switch to survey designer view
5. Switch to JSON view
6. Go to 4

The memory usage will quickly increase to 1+GB

### Specify your

* browser: Chrome
* browser version: 78
Als happens on Firefox, but at a much lower pace

* surveyjs platform (angular or react or jquery or knockout or vue):
* surveyjs version:

**Comment by tsv2013** [comment]
I'm working on the issue.
I've reproduced the memory leak in the Chrome Dev Tools memory profiler.
On your JSON memory (by profiler) increases in apprx 20Mb per 10 switches between Designer/JSON Editor tabs.
Unfortunately I've found the main leak source at this moment. According to memory profiler results there are a lot of small pieces were created during the tab switching.
I'll update this thread in case of any further results.

**Comment by tsv2013** [comment]
I've found several places in SurveyJS Creator with small leaks. They are related to survey property editors. On the other hand right now we're dramatically rewriting property editors and in the nearest future places I've found will not exist in the code.

We've discussed this issue with the team and decided to postpone this task after new SurveyJS Creator property editors will be released.

**Comment by SamMousa** [comment]
Thanks for the update, good luck with refactoring property editors :D --> if possible leave this open so that I get notified and can notify my users when it is fixed!

**Comment by tsv2013** [comment]
@SamMousa I definitely leave this issue open :-) Please feel free to ping me here

**Comment by gologames** [comment]
Some memory leaks were found and fixed in previous versions of SurveyJS Creator

**Comment by frankinedinburgh** [comment]
Im getting this same issue with version 1.9.42
When I load a large survey into the JSON tab and go to translations to edit labels the browser will run out of memory on scroll. 
I have the lazyRowsRendering set to true but still get this Error Code: out of memory. Half way down the page I dont see the translations and then the browser crashes

**Comment by andrewtelnov** [comment]
@frankinedinburgh Do you use Creator V2? What framework do you use and could you please share your JSON?

PS: Please create a new issue.

Thank you,
Andrew

**Comment by dmitrykurmanov** [comment]
@frankinedinburgh  @andrewtelnov  here is the new issue: https://github.com/surveyjs/survey-creator/issues/3346
